name: Release Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build the JAR file with Maven
        run: mvn clean package -B

      - name: Test with Maven
        run: mvn test -B

  deliver-jar:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build the JAR file with Maven
        run: mvn clean package -B

      - name: Verify if JAR file exists
        run: |
          ls -l target/
          ls -l target/*.jar

      - name: Upload the JAR file to GitHub as an artifact
        uses: actions/upload-artifact@v4  # Using v4 here
        with:
          name: example-bicycle-jar
          path: target/example-bicycle-0.0.1-SNAPSHOT.jar

  release:
    runs-on: ubuntu-latest
    needs: deliver-jar
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2

      - name: Download the JAR artifact
        uses: actions/download-artifact@v4  # Using v4 here
        with:
          name: example-bicycle-jar

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          files: example-bicycle-0.0.1-SNAPSHOT.jar  # Path without "target/"
